### ISSUE TITLE
Pypi package for PYDOP

### ISSUE THREAD

**Issue by mgv99** [onera/pydop#1]
Dear ONERA team,

Is it planned to add PYDOP to Pypi soon? I am starting a prototype project that will implement an SPL for mixture of experts (MoE) AI systems and this tool looks promising. For now, I will use it as a git dependency, but would be really cool to have it as a pip package as well. Thanks :)

Marcos Gomez

**Comment by gzoumix** [comment]
Dear Marcos,

Done: https://pypi.org/project/pydop/1.0/
Any suggestion/request on improving the library are welcomed :)

Best Regards,
Michael Lienhardt
